# Silso Keyboard Hoarders TOTEM - XIAO BLE dongle central

CONFIG_ZMK_KEYBOARD_NAME="KBHTotem"

CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

# Dongle is USB-powered, so do not let it sleep
CONFIG_ZMK_SLEEP=n

# Dongle is the central for both halves
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Required for your NAV mouse movement / scroll layer
CONFIG_ZMK_POINTING=y

# Keep stronger BLE transmit power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Ten host Bluetooth profiles on the dongle
# Active BLE connections:
# left half + right half + one BLE host when using OUT_BLE
CONFIG_BT_MAX_CONN=3

# Stored bonds:
# 10 host profiles + 2 keyboard halves
CONFIG_BT_MAX_PAIRED=12

# Let the dongle report the halves' battery level
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Dongle itself is USB-powered, so no fake 100% battery report
CONFIG_BT_BAS=n
